### ISSUE TITLE
make README and title more informative

### ISSUE THREAD

**Issue by jbloom** [dms-vep/SARS-CoV-2_Omicron_BA.1_spike_DMS_268C.59A#1]
@Bernadetadad, can you make the title of the README and the docs more specific to the project, such as describing the antibody. 

Sort of like here: https://github.com/dms-vep/SARS-CoV-2_Omicron_BA.1_spike_DMS_mAbs/blob/main/config.yaml#L18

And also note README needs to be updated separately.

**Comment by Bernadetadad** [comment]
done
